export { default as auth } from './auth'
export { default as customer } from './customer'
export { default as product } from './product'
export { default as products } from './products'
export { default as collection } from './collection'
export { default as order } from './order'
export { default as banners } from './banners'
export { default as faq } from './faq'
